In [1]:
%matplotlib ipympl

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# from scipy.ndimage import gaussian_filter

from __future__ import print_function
from matplotlib import pyplot as plt
import matplotlib
import matplotlib.patches as patches
from matplotlib.collections import PatchCollection
from matplotlib.patches import Rectangle
import matplotlib.colors as colors
import matplotlib.cm as cmx
from mpl_toolkits.axes_grid1 import make_axes_locatable
# from PIL import Image
from tqdm.notebook import trange, tqdm, tnrange
import time
from datetime import datetime

# import math
# import glob
import numpy as np


# import itertools
import os.path
import os
import sys
# from skimage.io import imread
import cv2

# import pandas as pd

# from scipy.signal import savgol_filter
# import pytesseract 
# from scipy.signal import find_peaks

matplotlib.rcParams.update({'font.size': 14})
plt.rcParams["font.family"] = "arial"


import importlib

import SimpleITK as sitk
# import imageio

In [2]:
## Import functions
PathToFunctions = '/Users/iracicot/Documents/GitHub/HySE_HypercubeFunctions/'
sys.path.append(PathToFunctions)
# from HySE_HypercubeFunctions import *
import HySE_HypercubeFunctions

## Indicate which wavelengths were used (Panel4, Panel2), in nm

# Wavelengths_list = np.array([566,494,590,518,614,542,638, 578,506,602,530,626,554,650])
# SavingPath = '/Users/iracicot/Library/CloudStorage/OneDrive-UniversityofCambridge/Data/PoM/EndoscopeVideo/20240529/'
# ## Locate the data to analyse
# Name = 'Hand_Moving'
# # Name = 'Flat'
# # Name = 'Columns'



Wavelengths_list = np.array([470,566,494,590,518,614,542,638, 482,578,506,602,530,626,554,650])
SavingPath = '/Users/iracicot/Library/CloudStorage/OneDrive-UniversityofCambridge/Data/PoM/EndoscopeVideo/20240524/'
## Locate the data to analyse
Name = 'Hand'

CropImDimensions = [166,680, 42,520] ## Dazzle, PoM


DataPath = SavingPath
vidPath = DataPath+Name+'.mpg'

In [3]:
EdgePos, Peaks, Peaks_dist = HySE_HypercubeFunctions.FindHypercube(vidPath, Wavelengths_list, PlotGradient=False, CropImDimensions=[166,680, 42,520], DarkMin=50, PlateauSize=17, 
                                                                   MaxPlateauSize=30, PeakHeight=0.4, ReturnPeaks=True, PeakDistance=15, WindowLength=3)

ATTENTION: ReturnPeaks is set to True. Be careful, the output will have three elements!
Add 'Help=True' in input for a list and description of all optional parameters 
Max plateau size set to 30
Min long dark size set to 50
Expected plateau size set to 17
Only importing the trace of the data
Cropping Image
Cropping image: x [166 : 680],y [42, 520]
Setting peak height to 0.4
Setting peak distance to 15

[18 21 18 18 18 21 18 25 15 20 19 17 18 21 18 18 18]
  separation: 76 - 17 plateaux, avg 18.88 frames +/- 2.14


[20 18 18 18 21 18 18 18 22 17 18 18 21 18 18 18 21]
  separation: 76 - 17 plateaux, avg 18.82 frames +/- 1.46


[17 18 18 21 18 18 18 21 19 17 18 21 18 18 18 21 18]
  separation: 76 - 17 plateaux, avg 18.65 frames +/- 1.37


[17 18 21 19 17 18 21 18 18 18 21 18 18 18 21 18 18]
  separation: 75 - 17 plateaux, avg 18.65 frames +/- 1.37


[18 21 18 18 18 21 18 18 18 21 18 18 18 21 18 18 18]
  separation: 75 - 17 plateaux, avg 18.71 frames +/- 1.27


[21 18 18 21 21 18 18 18 22 1

In [4]:
DataAll = HySE_HypercubeFunctions.ImportData(vidPath, CropImDimensions=CropImDimensions)

Cropping Image
Cropping image: x [166 : 680],y [42, 520]


In [5]:
Nsweep = 7

DataSweep = []
for Nc in range(0,len(EdgePos[Nsweep])):
    Data_c = DataAll[EdgePos[Nsweep][Nc,0]:EdgePos[Nsweep][Nc,0]+EdgePos[Nsweep][Nc,1], :,:]
    DataSweep.append(Data_c)

In [ ]:
Hypercube = HySE_HypercubeFunctions.SweepCoRegister(DataSweep, Wavelengths_list, ImStatic_Plateau=1, ImStatic_Index=8, Buffer=6)

Plot_Index outside default range. Set to 10, please set manually with Plot_Index
Static image: plateau 1, index 8. Use ImStatic_Plateau and ImStatic_Index to change it.
Buffer set to 6


  0%|          | 0/17 [00:00<?, ?it/s]

In [ ]:
importlib.reload(HySE_HypercubeFunctions)

HySE_HypercubeFunctions.PlotHypercube(Hypercube, Wavelengths=Wavelengths_list)

In [ ]:
SavingPathWithName = f'{SavingPath}{Name}_Sweep{Sweep}.mp4'

MakeHypercubeVideo(Hypercube, SavingPathWithName)